[tool.poetry]
name = "udify"
version = "0.1.0"
description = ""
authors = ["Dan Kondratyuk"]

[tool.poetry.dependencies]
python = "^3.6"
allennlp = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
